# Generated by Django 5.0.6 on 2024-06-03 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_product_cart_order_ordertoproduct_order_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_of_the_week',
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.product')),
            ],
        ),
    ]
