# Generated by Django 5.0.6 on 2024-06-02 19:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0002_product_cart_order_ordertoproduct_order_product_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training_session',
            name='training_plan',
        ),
        migrations.AddField(
            model_name='training_session',
            name='Profile',
            field=models.OneToOneField(default=74409, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training_session',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training_session',
            name='img',
            field=models.ImageField(null=True, upload_to='sessions/%y/%m/%d'),
        ),
        migrations.AddField(
            model_name='training_session',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='participant_limit',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.DeleteModel(
            name='Training_plan',
        ),
    ]
