# Generated by Django 5.0.6 on 2024-06-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0003_remove_product_product_of_the_week_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
