# Generated by Django 5.0.6 on 2024-06-03 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0006_alter_training_session_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='Profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.profile'),
        ),
    ]
