# Generated by Django 5.0.6 on 2024-06-09 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0007_alter_training_session_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='session_location',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='training_session',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='training_session',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='session_date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coach.training_session')),
            ],
        ),
        migrations.AlterField(
            model_name='training_session',
            name='location',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='coach.session_location'),
        ),
    ]
