# Generated by Django 5.0.6 on 2024-06-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0008_session_location_alter_training_session_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='categorie',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='training_session',
            name='categorie_secondary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
