# Generated by Django 5.0.6 on 2024-06-11 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0009_training_session_categorie_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name=''),
        ),
    ]
