# Generated by Django 5.0.6 on 2024-06-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0004_alter_productvariant_id'),
        ('coach', '0010_training_session_price'),
    ]

    operations = [
    ]
