# Generated by Django 5.0.6 on 2024-06-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0011_merge_20240614_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
