# Generated by Django 5.0.6 on 2024-06-14 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0012_alter_training_session_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorie',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='training_session',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.profile'),
        ),
    ]
