# Generated by Django 5.0.6 on 2024-06-14 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_categorie_alter_training_session_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training_session',
            old_name='categorie_secondary',
            new_name='type',
        ),
    ]
