# Generated by Django 5.0.6 on 2024-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0013_categorie_alter_training_session_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='profile2.png', upload_to='images/'),
        ),
    ]
