# Generated by Django 5.0.6 on 2024-06-16 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0014_alter_profile_image'),
        ('coach', '0014_rename_categorie_secondary_training_session_type'),
    ]

    operations = [
    ]
