# Generated by Django 5.0.6 on 2024-06-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0015_merge_20240616_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='training_session',
            name='small_sum',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
