# Generated by Django 5.0.6 on 2024-06-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0016_training_session_small_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
