# Generated by Django 5.0.6 on 2024-06-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0017_alter_training_session_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training_session',
            name='description',
            field=models.JSONField(null=True),
        ),
    ]
