# Generated by Django 5.0.6 on 2024-06-21 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0019_reviews_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.training_session'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='type',
            field=models.CharField(default='session', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.training_session'),
        ),
        migrations.AddField(
            model_name='ordertoproduct',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.training_session'),
        ),
        migrations.AddField(
            model_name='ordertoproduct',
            name='type',
            field=models.CharField(default='session', max_length=255),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.product'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.AlterField(
            model_name='ordertoproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='coach.product'),
        ),
    ]
