# Generated by Django 5.0.6 on 2024-06-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0021_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='training_session',
        ),
    ]
