# Generated by Django 5.0.6 on 2024-06-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0022_remove_order_training_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
