# Generated by Django 5.0.6 on 2024-06-24 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0023_remove_order_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoproduct',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coach.training_session'),
        ),
    ]
