# Generated by Django 5.0.6 on 2024-06-24 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0024_alter_ordertoproduct_training_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
        migrations.AddField(
            model_name='ordertoproduct',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
