# Generated by Django 5.0.6 on 2024-06-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0026_alter_ordertoproduct_training_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exp', models.CharField(default='1', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
