# Generated by Django 5.0.6 on 2024-06-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0027_alter_ordertoproduct_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertoproduct',
            name='training_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders_training_session', to='coach.training_session'),
        ),
    ]
