# Generated by Django 5.0.6 on 2024-06-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0027_coachrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachrequest',
            name='Profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coach.profile'),
        ),
    ]
