# Generated by Django 5.0.6 on 2024-06-26 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coach', '0028_alter_ordertoproduct_training_session'),
        ('coach', '0028_coachrequest_profile'),
    ]

    operations = [
    ]
