from coach.api.sign_up import signup
from coach.api.home import home
from coach.api.sign_in import signin
from coach.api.logout import sign_out
from coach.api.session import session
from coach.api.shop import shop
from coach.api.products import products
from coach.api.training_session.create_session import add_session,update_session_img
from coach.api.update_session import update_session
from coach.api.productslist import product_list
from coach.api.cart import cart
from coach.api.add_to_cart import add_to_cart
from coach.api.dashboard import dashboard
from coach.api.session_creation import session_creation
from coach.api.delete_cart_item import delete_cart_item_handler
from coach.api.add_order import add_order_handler
from coach.api.profile import profile
from coach.api.stats import stats
from coach.api.delete_session import delete_session
